# Spring properties
spring:
  application:
    name: partner-contactdata-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10

# Enable hystrix for feign
feign:
    hystrix:
        enabled: true

# HTTP Server
server:
  port: 1004   # HTTP (Tomcat) port

#resolve the service time-out exception
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000