# Spring properties
spring:
  h2:
    console:
      enabled: true
  application:
    name: partner-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

# HTTP Server
server:
  port: 1002   # HTTP (Tomcat) port