# Spring properties
spring:
  application:
    name: partner-service  # the Service ID
  h2:
    console:
      enabled: true

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port
