# Spring
spring:
  application:
    name: monitor-service

# Eureka
eureka:
  client:
    registryFetchInvervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 9999 # HTTP (Tomcat) port

# Service Monitoring
turbine:
  clusterNameExpression: new String("default")
  appConfig: partner-contact-service