# Spring properties
spring:
  application:
    name: frontend-service

# Discovery Server Access
eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

# API Proxy configuration
zuul:
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 10000
  routes:
    partner-service:
      path: /partner/**
      serviceId: partner-service
      stripPrefix: false
    contactdata-service:
      path: /contactdata/**
      serviceId: contactdata-service
      stripPrefix: false
    partner-contactdata-service:
      path: /partner-contactdata/**
      serviceId: partner-contactdata-service
      stripPrefix: false

#resolve the service time-out exception
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000