# Spring properties
spring:
  application:
    name: frontend-service # the Service ID

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# API Proxy configuration
zuul:
  routes:
    partner-service:
      path: /partners/**
      serviceId: partner-service
      stripPrefix: true
    contact-service:
      path: /contacts/**
      serviceId: contact-service
      stripPrefix: true
    partner-contact-service:
      path: /partnercontacts/**
      serviceId: partner-contact-service
      stripPreifx: true
