# Spring properties
spring:
  application:
    name: frontend-service # the Service ID

# Discovery Server Access
eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/


# API Proxy configuration
zuul:
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 10000
  routes:
    partner-service:
      path: /partners/**
      serviceId: partner-service
      stripPrefix: false
    contact-service:
      path: /contacts/**
      serviceId: contact-service
      stripPrefix: false
    partner-contact-service:
      path: /partnercontacts/**
      serviceId: partner-contact-service
      stripPreifx: false

#resolve the service time-out exception
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000