# Spring properties
spring:
  h2:
      console:
        enabled: true
  application:
    name: contact-service # the Service ID

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port
