# Spring properties
spring:
  application:
    name: contact-service   # the Service ID
  h2:
    console:
      enabled: true
  
# Register this Service as Eureka Client with the Eureka Server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port
